plugins { id 'com.android.application' }

android {
    namespace 'my.cigunofal.kuasaimatematik'
    compileSdk 35

    defaultConfig {
        applicationId 'my.cigunofal.kuasaimatematik'
        minSdk 21
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
